twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']

when@test:
    twig:
        strict_variables: true
<<<<<<< HEAD
        form_themes: ['bootstrap_5_horizontal_layout.html.twig']
=======
>>>>>>> parent of 99add47 (login/registratie gemaakt)
